CREATE TABLE NODOS ( 
    id_nodo NUMBER PRIMARY KEY, 
    id_persona NUMBER,
    ubicacion VARCHAR2(100) NOT NULL, 
    tipo VARCHAR2(20) CHECK (tipo IN ('Consumidor','Prosumidor','Bateria')), 
    saldo_cuenta NUMBER DEFAULT 0 CHECK (saldo_cuenta >= 0), -- créditos
    perfil_consumo VARCHAR2(20) -- solo para Consumidores
    );

CREATE TABLE LECTURAS_HISTORICAS ( 
    id_lectura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    id_nodo NUMBER NOT NULL, 
    tick_hora DATE NOT NULL, -- timestamp simulado 
    produccion_kwh NUMBER DEFAULT 0, 
    consumo_kwh NUMBER DEFAULT 0, 
    excedente_neto NUMBER, 
    FOREIGN KEY (id_nodo) REFERENCES NODOS(id_nodo)
    );

CREATE TABLE TRANSACCIONES ( 
    id_transaccion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    id_vendedor NUMBER NOT NULL, 
    id_comprador NUMBER NOT NULL, 
    kwh NUMBER NOT NULL, 
    precio_unitario NUMBER NOT NULL, 
    fecha_transaccion TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    FOREIGN KEY (id_vendedor) REFERENCES NODOS(id_nodo), 
    FOREIGN KEY (id_comprador) REFERENCES NODOS(id_nodo), 
    CONSTRAINT chk_kwh_pos CHECK (kwh > 0), 
    CONSTRAINT chk_precio_pos CHECK (precio_unitario > 0)
    );

CREATE TABLE CONFIG_TARIFAS ( 
    hora NUMBER(2) PRIMARY KEY CHECK (hora BETWEEN 0 AND 23), 
    precio_base_kwh NUMBER NOT NULL
    );
    
-- Disparador (Trigger)
CREATE OR REPLACE TRIGGER trg_validar_saldo
BEFORE INSERT ON TRANSACCIONESFOR EACH ROWDECLARE v_saldo_comprador NUMBER;
BEGIN
    SELECT saldo_cuenta 
    INTO v_saldo_comprador 
    FROM NODOS 
    WHERE id_nodo = :NEW.id_comprador; 
    IF v_saldo_comprador < (:NEW.kwh * :NEW.precio_unitario) 
        THEN RAISE_APPLICATION_ERROR(-20001, 'Saldo insuficiente para realizar la compra'); 
    END IF;
END; 

-- REVISAR  -----------------------------------------------------
CREATE OR REPLACE PROCEDURE actualizar_saldo_y_lecturas (
    p_id_nodo IN NUMBER,
    p_kwh IN NUMBER,
    p_precio IN NUMBER,
    p_tipo_operacion IN VARCHAR2 -- 'COMPRA' o 'VENTA'
) AS
    v_monto NUMBER := p_kwh * p_precio;
BEGIN
    IF p_tipo_operacion = 'COMPRA' THEN
        UPDATE NODOS SET saldo_cuenta = saldo_cuenta - v_monto WHERE id_nodo = p_id_nodo;
        INSERT INTO LECTURAS_HISTORICAS (id_nodo, tick_hora, consumo_kwh) 
        VALUES (p_id_nodo, SYSDATE, p_kwh);
    ELSIF p_tipo_operacion = 'VENTA' THEN
        UPDATE NODOS SET saldo_cuenta = saldo_cuenta + v_monto WHERE id_nodo = p_id_nodo;
        INSERT INTO LECTURAS_HISTORICAS (id_nodo, tick_hora, produccion_kwh) 
        VALUES (p_id_nodo, SYSDATE, p_kwh);
    END IF;
END;

-- ---------------------------------------------------------------
-- Tarifas de los casos de prueba provistos en el TP
-- ---------------------------------------------------------------
INSERT INTO CONFIG_TARIFAS (hora, precio_base_kwh) VALUES (10, 1.00); [cite: 678]
INSERT INTO CONFIG_TARIFAS (hora, precio_base_kwh) VALUES (12, 1.50); [cite: 679]
INSERT INTO CONFIG_TARIFAS (hora, precio_base_kwh) VALUES (14, 1.00); [cite: 680]
INSERT INTO CONFIG_TARIFAS (hora, precio_base_kwh) VALUES (15, 1.20); [cite: 681]
INSERT INTO CONFIG_TARIFAS (hora, precio_base_kwh) VALUES (18, 2.00); [cite: 682]

-- Nodos del Caso 1 y Caso 4
INSERT INTO NODOS (id_nodo, ubicacion, tipo, saldo_cuenta, perfil_consumo) 
VALUES (1, 'Zona Norte', 'Consumidor', 100.00, 'Residencial'); [cite: 685]

INSERT INTO NODOS (id_nodo, ubicacion, tipo, saldo_cuenta) 
VALUES (2, 'Zona Centro', 'Prosumidor', 50.00); [cite: 686]

-- Nodo Batería Comunitaria (Nodo 99)
INSERT INTO NODOS (id_nodo, ubicacion, tipo, saldo_cuenta) 
VALUES (99, 'Estación Central', 'Bateria', 999999); [cite: 752]

COMMIT;

-- ---------------------------------------------------------------